# Generated by Django 4.1.4 on 2022-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_full_name', models.CharField(max_length=100)),
                ('user_institution', models.CharField(max_length=100)),
            ],
        ),
    ]
