# Generated by Django 4.1.4 on 2022-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_user_user_atcoder_handle_user_user_cf_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
