# Generated by Django 4.1.4 on 2022-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=1000)),
                ('blog_content', models.CharField(blank=True, max_length=200000)),
                ('like_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
