# Generated by Django 4.1.4 on 2022-12-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestSetter',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
